version: '3.1'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - local:/data
  mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
          - '1025:1025'
          - '8025:8025'
  db:
    image: 'mysql:8.0'
    ports:
      - 33063:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - 'local:/var/lib/mysql'
  postgre:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgre:/var/lib/postgresql/data
volumes:
  local:
    driver: local
  postgre:
    driver: local
networks:
  default:
    external:
      name: local